encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en
permalink: '/blog/:year/:month/:day/:title/'
whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3
  
sass:
  style: compressed
  
url: "http://nesterof.com"
baseurl: 
title: How ToDo everything
description: My short notes about everything
keywords: 'debian,xen,linux,blog'
author:
  name: Nesterov Alexey
  job_title: null
  location: Vladivostok
  email: a@nesterov.tk
  social_links:
    - name: facebook
      url: null
    - name: github
      url: 'https://github.com/vertigra'
    - name: instagram
      url: null
    - name: linkedin
      url: null
    - name: stackoverflow
      url: null
    - name: twitter
      url: 'https://twitter.com/vertigraDevel'
    - name: vk
      url: null
home:
  section1: <h1>How ToDo everything</h1>
  section2: <h2>My short notes</h2>
  section3: >-
    <div class="social-links"><a class="ico-github btn"
    href="https://github.com/vertigra/nesterof.com" title="View on
    GitHub"></a></div>
blog:
  cc_license: null
  cc_license_image: null
  footer_content: My short notes about everything.
disqus:
  shortname: nesterof-com
  public_key:
google_analytics: UA-98112747-2
addthis_public_id: ra-59c1a29328e870df
paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
